### ISSUE TITLE
在Windows下網頁右邊會多出一條空行

### ISSUE THREAD

**Issue by CodinCat** [jsdc-core/jsdc2016#25]
`#sponsor-line`若直接使用 100vw，在Windows內會把捲軸的寬度也算進去，網頁因此出現橫向捲軸，最右邊就多出一行捲軸的空行

![ashampoo_snap_2016 06 02_22h53m05s_001_](https://cloud.githubusercontent.com/assets/3193344/15749428/e911865e-2914-11e6-9163-e7b1cfb52764.png)

原本的100vw：

``` scss
  #sponsor-line{
    position: absolute;
    top: 58%;
    left: 0;
    &:after {
      background: $jsdc-b;
      content: '';
      display: inline-block;
      height: 1px;
      width: 100vw;
    }
  }
```

應修正為：

``` scss
  #sponsor-line{
    position: absolute;
    top: 58%;
    left: 0;
    width: 100%;
    &:after {
      background: $jsdc-b;
      content: '';
      display: inline-block;
      height: 1px;
      width: 100%;
    }
  }
```
